---
- name: ensure kernal is newer than 3.11 (Docker requirement)
  fail:
    msg="Kernel is too old to run docker. Update kernel"
  when: kernel | version_compare('3.11', '<')

- name: Install dependencies
  apt: name={{item}} state=present update_cache=yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - apparmor
    - "linux-image-extra-{{ansible_kernel}}"

- name: Add docker GPG key
  apt_key:
    keyserver=hkp://p80.pool.sks-keyservers.net:80
    id=58118E89F3A912897C070ADBF76221572C52609D

# shouldn't assume ubuntu14
- name: Create docker.list file
  copy:
    dest=/etc/apt/sources.list.d/docker.list
    content='deb https://apt.dockerproject.org/repo ubuntu-trusty main'

- name: Install docker
  apt: name=docker-engine state=present update_cache=yes

- name: Install git
  apt: name=git state=present update_cache=yes

- name: Start docker service
  service: name=docker state=started
